version: '3'
services:
  api:
    image: kosamtech/fastapi
    depends_on:
      - postgres_db
    command: sh -c "chmod +x /usr/src/app/entrypoint.sh && sh /usr/src/app/entrypoint.sh"
    ports: 
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres_db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - PORT=8000
  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
    ports:
      - 5433:5432  
    volumes:
      - fastapi-db:/var/lib/postgresql/data
      
volumes:
  fastapi-db: