GET http://127.0.0.1:8000

###
GET http://127.0.0.1:8000/posts

###
POST  http://127.0.0.1:8000/posts/create
Content-Type: application/json

{
  "title": "Post Title",
  "content": "Post Content"
}


###
GET http://127.0.0.1:8000/posts/detail/5


###
GET http://127.0.0.1:8000/posts/latest

###
DELETE  http://127.0.0.1:8000/posts/delete/1

###
PUT http://127.0.0.1:8000/posts/edit/1
Content-Type: application/json

{
  "title": "Update post title",
  "content": "Updated post content"
}


###
GET http://127.0.0.1:8000/docs