name: Build and Deploy Code

on: 
  push:
    branches: 
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling get repo
        uses: actions/checkout@v2
      - name: say hi to kosam
        run: echo "Hello kosam"  
        